---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop react-app
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm react-app
      ignore_errors: yes

    - name: remove project-image
      command: docker rmi react-app
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t hechem220/react-img .

    - name: Push Image to dockerhub
      command: docker push hechem220/react-img

    - name: run container
      command: docker run -d --name react-app -p 5000:80 hechem220/react-img
