---
- name: Deployment 
  hosts: webservers
  become: yes
  tasks:
    - name: Pull the Docker image from DockerHub
      docker_image:
        name: hechem220/react-img
        tag: latest
        pull: yes
        
    - name: Stop any running container with the same name
      docker_container:
        name: react-app-container
        state: stopped
        force_kill: true
      ignore_errors: yes

    - name: Remove the old container
      docker_container:
        name: react-app-container
        state: absent
      ignore_errors: yes

    - name: Run the new container
      docker_container:
        name: react-app-container
        image: hechem220/react-img:latest
        state: started
        ports:
          - "3000:3000"
        restart_policy: always
