---
- name: Deployment 
  hosts: webservers
  become: yes
  tasks:
    - name: Pull the Docker image from DockerHub
      command: docker pull hechem220/react-img:latest

    - name: Stop any running container with the same name
      command: docker stop react-app-container
      ignore_errors: yes

    - name: Remove the old container
      command: docker rm react-app-container
      ignore_errors: yes

    - name: Run the new container
      command: docker run -d --name react-app-container -p 80:80 --restart always hechem220/react-img:latest

