<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
=======
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
>>>>>>> f0e1b54ef2b0a98cf8c4d9f9d43112fd122be8fd
